rule summarize:
    input:
        #TODO
    output:
        #TODO
    shell:
        "wc -c {input} > {output}"

rule extract:
    input:
        #TODO
    output:
        #TODO
    shell:
        "sed 's/^[ ]*//' {input} | cut -f1 -d ' ' > {output}"
