localrules: all, extract

SAMPLES, = glob_wildcards("{samples}.fasta")

rule all:
    input:
        expand("{samples}.sum", samples=SAMPLES)

rule do_summarize:
    input:
        "{samples}.fasta"
    output:
        "{samples}.sum"
    message:
        "summarizing {input} to {output}"
    shell:
        "wc -c {input} > {output}"

rule clean:
    shell:
        "rm -f *.sum"
